# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kdelibs4support

# >> macros
# << macros

# >> bcond_with
# << bcond_with

# >> bcond_without
# << bcond_without

Summary:    KDE Frameworks 5 Tier 4 module with porting aid from KDELibs 4
Version:    5.2.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kdelibs4support.yaml
Source101:  kdelibs4support-rpmlintrc
Requires:   kf5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5X11Extras)
BuildRequires:  pkgconfig(Qt5Svg)
BuildRequires:  pkgconfig(Qt5PrintSupport)
BuildRequires:  pkgconfig(Qt5Designer)
BuildRequires:  pkgconfig(Qt5DesignerComponents)
BuildRequires:  pkgconfig(x11-xcb)
BuildRequires:  pkgconfig(sm)
BuildRequires:  pkgconfig(openssl)
BuildRequires:  kf5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  qt5-qttools-qtdesigner
BuildRequires:  kcompletion-devel
BuildRequires:  kconfig-devel
BuildRequires:  kconfigwidgets-devel
BuildRequires:  kcrash-devel
BuildRequires:  kdesignerplugin-devel
BuildRequires:  kglobalaccel-devel
BuildRequires:  kdoctools-devel
BuildRequires:  kguiaddons-devel
BuildRequires:  ki18n-devel
BuildRequires:  kiconthemes-devel
BuildRequires:  kio-devel
BuildRequires:  knotifications-devel
BuildRequires:  kparts-devel
BuildRequires:  kservice-devel
BuildRequires:  ktextwidgets-devel
BuildRequires:  kunitconversion-devel
BuildRequires:  kwidgetsaddons-devel
BuildRequires:  kwindowsystem-devel
BuildRequires:  kxmlgui-devel

%description
KDE Frameworks 5 Tier 4 module with porting aid from KDELibs 4


%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   kauth-devel
Requires:   kconfigwidgets-devel
Requires:   kcoreaddons-devel
Requires:   kcrash-devel
Requires:   kdesignerplugin-devel
Requires:   kdoctools-devel
Requires:   kemoticons-devel
Requires:   kguiaddons-devel
Requires:   kiconthemes-devel
Requires:   kitemmodels-devel
Requires:   kinit-devel
Requires:   knotifications-devel
Requires:   kparts-devel
Requires:   ktextwidgets-devel
Requires:   kunitconversion-devel
Requires:   kwindowsystem-devel

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kf5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kf5_make_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%doc COPYING.LIB README.md
%{_kf5_bindir}/kf5-config
%{_kf5_bindir}/kdebugdialog5
%{_kf5_libdir}/libKF5KDELibs4Support.so.*
%{_kf5_libexecdir}/*
%{_kf5_plugindir}/*
%{_mandir}/man1/*
%{_kf5_servicesdir}/*.protocol
%{_kf5_servicesdir}/*.desktop
%{_kf5_servicesdir}/qimageioplugins/*.desktop
%{_kf5_servicetypesdir}/*.desktop
%{_kf5_servicesdir}/kded/networkstatus.desktop
%{_kf5_datadir}/kdoctools/customization
%{_kf5_datadir}/locale/*
%{_kf5_sharedir}/locale/en_US/kf5_entry.desktop
%{_kf5_sharedir}/locale/kf5_all_languages
%{_kf5_datadir}/widgets/
%{_kf5_datadir}/kssl/ca-bundle.crt
%{_kf5_configdir}/colors
%{_kf5_configdir}/kdebug.areas
%{_kf5_configdir}/kdebugrc
%{_kf5_configdir}/ksslcalist
%{_kf5_htmldir}/en/kdebugdialog5
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_kf5_libdir}/libKF5KDELibs4Support.so
%{_kf5_cmakedir}/KF5KDELibs4Support/
%{_kf5_cmakedir}/KF5KDE4Support/
%{_kf5_cmakedir}/KDELibs4/
%{_kf5_includedir}/kdelibs4support_version.h
%{_kf5_includedir}/KDELibs4Support/
%{_kf5_dbusinterfacesdir}/*.xml
# >> files devel
# << files devel
